version: '3'

services:
  web:
    build: .
    volumes:
      - ssl_certs:/etc/ssl/certs
      - ssl_private:/etc/ssl/private
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ssl_certs:/etc/ssl/certs
      - ssl_private:/etc/ssl/private
    depends_on:
      - web

volumes:
  ssl_certs:
  ssl_private:
